add Extents as input to map + test
MakieOrg/Tyler.jl pull request #22
Opened 2023-01-31 19:56 UTC by alex-s-gardner

2023-01-31 22:30 UTC, rafaqz reviewed
LGTM

2023-02-01 08:16 UTC, rafaqz requested changes

2023-02-01 08:16 UTC, rafaqz commented on test/Manifest.toml
> -version = "1.0.2+0"
Maybe remove all these manifest changes

2023-02-14 16:49 UTC, rafaqz commented on test/Manifest.toml
> -version = "1.0.2+0"
bump

2023-02-20 13:26 UTC, rafaqz commented on src/Tyler.jl
> +function Map(rect::Union{Rect,Extent}, input_cs=wgs84;
```suggestion
function Map(extent::Union{Rect,Extent}, input_cs=wgs84;
```

2023-02-21 23:32 UTC, rafaqz commented
Damn I messed up the merge somehow.

2023-03-02 19:13 UTC, alex-s-gardner reviewed
Looks good... are we ready merge?

2023-03-02 21:45 UTC, rafaqz commented
No, the tests are not passing!

I'm not sure how this PR changes the number of tiles downloaded

2023-03-02 21:54 UTC, rafaqz commented
Oh you have just changed the number of tiles and the tests slightly. Fix that and we can merge

2023-03-03 22:25 UTC, merged

2023-03-03 22:26 UTC, rafaqz commented
Thanks

2023-03-03 22:31 UTC, alex-s-gardner commented
@rafaqz thank you for your patience as a battle git